### ISSUE TITLE
stexls 1.5.1 trefier setting in settings.JSON wront type

### ISSUE THREAD

**Issue by kohlhase** [slatex/stexls#10]
The settings file that came with stexls had a type error, 
```
  "stexls.enableTrefier": true ,
```
I changed it to 
```
  "stexls.enableTrefier": "full" ,
```
as recommended.

**Comment by kohlhase** [comment]
and then nothing happens, but I get a settings interface, and then I changed it back to "enabled", and now it downloaded a tensorflow model. 

Ah, and then it eventually also starts linting.

**Comment by Mari6814** [comment]
It being "true" is because user settings are persistent even between versions. And the setting was of type bool in the old version.
The new version uses the strings "disabled", "enabled" and "full".
My recommended value is "enabled" because "full" will apply the model to every file that is being linted, which is very very slow.
