### ISSUE TITLE
spurious error reported? 

### ISSUE THREAD

**Issue by kohlhase** [slatex/stexls#13]
In `MathHub/MiKoMH/IWGS/source/vci/snip/gitlabhub-intro.tex` I get a couple of error messages. 
<img width="779" alt="Screenshot 2021-05-21 at 14 15 56" src="https://user-images.githubusercontent.com/4037538/119135921-506da100-ba3f-11eb-8eb9-b6ad86f58f66.png">
They are incorrect, `git?remote-repository` is defined in `MathHub/MiKoMH/TDM/source/vc/en/git.tex`.

**Comment by Mari6814** [comment]
This works on my end?

Are you sure you didn't rename a folder or file or something?

You may have changed some file that broke the import chain between these two,
but because of how large the workspace is, it will take a while to compile this file again and realize that the
import chain has been fixed.

If you save gitlabhub-intro.tex it will be added to a high priority linting queue and linted as soon as the processor has the time.

**Comment by kohlhase** [comment]
OK, then I will just wait.

**Comment by kohlhase** [comment]
and close the error when it goes away.

**Comment by Mari6814** [comment]
If you have not updated stexls since yesterday, a bug may also be the cause.
It prevented files that do not have references to themselves from being linted.

**Comment by kohlhase** [comment]
OK, I did not, so I will try now.

**Comment by Mari6814** [comment]
And you should not have to wait more than a few seconds if you save the file.
Unless you notice the "Linting: xxxx files" notification never ticking down.
That could mean that some other file is preventing the process from continuing.
